services:
  - type: web
    name: ai-content-writer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GROQ_API_KEY
        fromEnv: GROQ_API_KEY
      # Unset proxy variables to prevent interference with httpx
      - key: HTTP_PROXY
        value: ""
      - key: HTTPS_PROXY
        value: ""
